
float32 roll_rate_integ	    # roll rate inegrator
float32 pitch_rate_integ	# pitch rate integrator
float32 yaw_rate_integ	    # yaw rate integrator
float32 roll_rate
float32 pitch_rate
float32 yaw_rate
float32 roll_rate_sp
float32 pitch_rate_sp
float32 yaw_rate_sp
float32 roll_rate_err
float32 pitch_rate_err
float32 yaw_rate_err
float32 roll_rate_int
float32 pitch_rate_int
float32 yaw_rate_int
float32 roll_att_control
float32 pitch_att_control
float32 yaw_att_control
